@extends('layouts.teacher')

@section('content')
<div class="w-full p-3 max-h-screen overflow-auto">
    <h1 class="text-2xl">PDF FILE ATTENDANCE RECORD</h1>
    <div class="my-1"></div>
    <div class="flex gap-2">
        <a class="bg-gray-500 p-2 rounded-lg text-white" href="/attendance">BACK</a>
        @php ($tw = Vite::asset('resources/css/app.css'))
        <button class="bg-blue-500 p-2 rounded-lg text-white" onclick="printJS({printable: 'printableRecords', type: 'html', showModal: true, css: '{{ $tw }}' })">PRINT</button>
    </div>
    <div id="printableRecords" class="container mx-auto max-w-[500px]">
        <div class="flex">
            <img class="w-32 h-32 object-cover rounded shadow" src="{{ $info->image() }}" alt="Student Profile">
            <div class="flex flex-col justify-center ml-3">
                <p class="font-bold">STUDENT ID: {{ $info->student_number }}</p>
                <p>FIRST NAME: {{ $info->first_name }}</p>
                @if ($info->middle_name !== null)
                <p>MIDDLE NAME: {{ $info->middle_name }}</p>
                @endif
                <p>LAST NAME: {{ $info->last_name }}</p>
            </div>
        </div>
        <table class="min-w-full bg-white">
            <thead class="text-left">
                <th class="py-2 px-4 border-b-2 border-gray-300">Date</th>
                <th class="py-2 px-4 border-b-2 border-gray-300">Time</th>
                <th class="py-2 px-4 border-b-2 border-gray-300">Action</th>
            </thead>
            <tbody>
                @foreach ($info->gateLogs()->orderBy('day', 'DESC')->orderBy('time', 'DESC')->get() as $log)
                <tr>
                    <td class="py-2 px-4 border-b border-gray-300">{{ $log->day }}</td>
                    <td class="py-2 px-4 border-b border-gray-300">{{ date_create($log->time)->format('g:i:s A') }}</td>
                    <td class="py-2 px-4 border-b border-gray-300 font-bold @if ($log->type === 'IN') text-green-500 @else text-red-500 @endif">{{ $log->type }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <p class="text-xs mt-3">Generated by {{ Auth::user()->getFullname() }} @ {{ date('F d, Y g:i:s A') }}</p>
    </div>
</div>
@endsection