@extends('layouts.admin')

@section('content')
<div class="w-full p-8 max-h-screen overflow-auto bg-gradient-to-br from-blue-50 to-indigo-50">
    <h1 class="text-3xl text-blue-800 font-bold mb-6 tracking-tight">Attendance Record</h1>
    
    <div class="flex gap-3 mb-8">
        <a class="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg text-white transition-all duration-200 shadow-md hover:shadow-lg flex items-center gap-2" href="/employee">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
            Back
        </a>
        @php ($tw = Vite::asset('resources/css/app.css'))
        <button class="bg-yellow-500 hover:bg-yellow-600 px-4 py-2 rounded-lg text-blue-900 font-semibold transition-all duration-200 shadow-md hover:shadow-lg flex items-center gap-2" onclick="printJS({printable: 'printableRecords', type: 'html', showModal: true, css: '{{ $tw }}' })">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print
        </button>
    </div>

    <div id="printableRecords" class="container mx-auto max-w-2xl bg-white p-8 rounded-xl shadow-xl">
        <div class="flex items-start gap-8">
            <img class="w-40 h-40 object-cover rounded-xl shadow-lg border-2 border-blue-200" src="{{ $user->image() }}" alt="Student Profile">
            <div class="flex-1 space-y-3">
                <div class="bg-blue-50 p-4 rounded-lg">
                    <h2 class="text-xl font-bold text-blue-800 mb-1">{{ $user->first_name }} {{ $user->middle_name ? substr($user->middle_name, 0, 1) . '. ' : '' }}{{ $user->last_name }}</h2>
                    <p class="text-blue-600">ID: {{ $user->employee_id }}</p>
                </div>
            </div>
        </div>

        <div class="mt-8 overflow-hidden rounded-lg border border-blue-100">
            <table class="min-w-full bg-white">
                <thead>
                    <tr class="bg-blue-600 text-white">
                        <th class="py-3 px-6 text-left">Date</th>
                        <th class="py-3 px-6 text-left">Time</th>
                        <th class="py-3 px-6 text-left">Action</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-blue-100">
                    @foreach ($user->gateLogs()->orderBy('day', 'DESC')->orderBy('time', 'DESC')->get() as $log)
                    <tr class="hover:bg-blue-50 transition-colors">
                        <td class="py-3 px-6">{{ $log->day }}</td>
                        <td class="py-3 px-6">{{ date_create($log->time)->format('g:i:s A') }}</td>
                        <td class="py-3 px-6">
                            <span class="px-3 py-1 rounded-full text-sm font-semibold @if ($log->type === 'IN') bg-green-100 text-green-700 @else bg-red-100 text-red-700 @endif">
                                {{ $log->type }}
                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        
        <p class="text-sm mt-6 text-blue-600 italic">Generated by {{ Auth::user()->getFullname() }} (ADMIN) on {{ date('F d, Y g:i:s A') }}</p>
    </div>
</div>
@endsection
